from ydata.dataset.multidataset import MultiTableSchema

class SchemaValidator:
    def check_independent_tables(self, schema: MultiTableSchema): ...
    def check_no_relations(self, schema: MultiTableSchema): ...
    def check_circular_relationships(self, schema: MultiTableSchema): ...
    def check_indirect_relationships(self, schema: MultiTableSchema): ...
    def check_self_reference(self, schema: MultiTableSchema): ...
    def get_warnings(self, schema: MultiTableSchema): ...
