
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-20T15:07:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ee7ceaf67cf4aafa65188e4aa7194ea6df411e3",
 "version": "1.2.0.post0.dev481"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
