from .database import (
    connect_to_db,
    fetch_data,
    fetch_medical_records,
    insert_medical_record,
    update_medical_record,
    delete_medical_record,
    fetch_patients,
    fetch_doctors,
    fetch_services,
    generate_report,
    insert_patient,
    insert_doctor,
    insert_medical_service,
    fetch_patient_by_id,
    fetch_doctor_by_id,
    fetch_service_by_id,
)