from _typeshed import Incomplete

def skewness(col, data): ...

class MultiModalNumberTransformer:
    num_modes: Incomplete
    model: Incomplete
    means: Incomplete
    stds: Incomplete
    def __init__(self, num_modes: int = 5) -> None: ...
    def fit(self, data): ...
    def transform(self, data): ...
    def inverse_transform(self, data): ...
