from _typeshed import Incomplete
from enum import Enum

class EskmoError(Enum):
    BASE: str
    LOGIN: str
    ACCOUNT_TAG_EXISTS: str
    SERVER: str
    OPERATION_FAILED: str
    NETWORK: str
    REQUEST_TIMEOUT: str

ERROR_HIERARCHY: Incomplete

class BaseError(Exception): ...
class LoginError(BaseError): ...
class AccountTagExistsError(LoginError): ...
class ServerError(BaseError): ...
class OperationFailedError(BaseError): ...
class NetworkError(OperationFailedError): ...
class RequestTimeoutError(NetworkError): ...
