from jthreads.looping_thread import LoopingThread
from threading import Thread
from typing import Any, Callable

__all__ = ['Timer', 'Interval']

class Timer(Thread):
    def __init__(self, time: float, cancelPollingTime: float, callback: Callable[[], Any]) -> None: ...
    def cancel(self) -> None: ...
    def run(self) -> None: ...

class Interval(LoopingThread):
    def __init__(self, interval: float, callback: Callable[[], Any]) -> None: ...
    def loop(self) -> None: ...
