# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .agents_search_request_search_item_order_by_value import AgentsSearchRequestSearchItemOrderByValue
from .agents_search_request_search_item_order_by_direction import AgentsSearchRequestSearchItemOrderByDirection
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class AgentsSearchRequestSearchItemOrderBy(UncheckedBaseModel):
    value: AgentsSearchRequestSearchItemOrderByValue
    direction: AgentsSearchRequestSearchItemOrderByDirection

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
