# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['pyband',
 'pyband.messages',
 'pyband.messages.band',
 'pyband.messages.band.bandtss',
 'pyband.messages.band.bandtss.v1beta1',
 'pyband.messages.band.feeds',
 'pyband.messages.band.feeds.v1beta1',
 'pyband.messages.band.globalfee',
 'pyband.messages.band.globalfee.v1beta1',
 'pyband.messages.band.oracle',
 'pyband.messages.band.oracle.v1',
 'pyband.messages.band.restake',
 'pyband.messages.band.restake.v1beta1',
 'pyband.messages.band.tss',
 'pyband.messages.band.tss.v1beta1',
 'pyband.messages.band.tunnel',
 'pyband.messages.band.tunnel.v1beta1',
 'pyband.messages.cosmos',
 'pyband.messages.cosmos.bank',
 'pyband.messages.cosmos.bank.v1beta1',
 'pyband.messages.cosmos.distribution',
 'pyband.messages.cosmos.distribution.v1beta1',
 'pyband.messages.cosmos.gov',
 'pyband.messages.cosmos.gov.v1beta1',
 'pyband.messages.cosmos.staking',
 'pyband.messages.cosmos.staking.v1beta1',
 'pyband.proto',
 'pyband.proto.amino',
 'pyband.proto.band',
 'pyband.proto.band.bandtss',
 'pyband.proto.band.bandtss.v1beta1',
 'pyband.proto.band.base',
 'pyband.proto.band.base.node',
 'pyband.proto.band.base.node.v1',
 'pyband.proto.band.base.oracle',
 'pyband.proto.band.base.oracle.v1',
 'pyband.proto.band.feeds',
 'pyband.proto.band.feeds.v1beta1',
 'pyband.proto.band.globalfee',
 'pyband.proto.band.globalfee.v1beta1',
 'pyband.proto.band.oracle',
 'pyband.proto.band.oracle.v1',
 'pyband.proto.band.restake',
 'pyband.proto.band.restake.v1beta1',
 'pyband.proto.band.rollingseed',
 'pyband.proto.band.rollingseed.v1beta1',
 'pyband.proto.band.tss',
 'pyband.proto.band.tss.v1beta1',
 'pyband.proto.band.tunnel',
 'pyband.proto.band.tunnel.v1beta1',
 'pyband.proto.cosmos',
 'pyband.proto.cosmos.app',
 'pyband.proto.cosmos.app.runtime',
 'pyband.proto.cosmos.app.runtime.v1alpha1',
 'pyband.proto.cosmos.app.v1alpha1',
 'pyband.proto.cosmos.auth',
 'pyband.proto.cosmos.auth.module',
 'pyband.proto.cosmos.auth.module.v1',
 'pyband.proto.cosmos.auth.v1beta1',
 'pyband.proto.cosmos.authz',
 'pyband.proto.cosmos.authz.module',
 'pyband.proto.cosmos.authz.module.v1',
 'pyband.proto.cosmos.authz.v1beta1',
 'pyband.proto.cosmos.autocli',
 'pyband.proto.cosmos.autocli.v1',
 'pyband.proto.cosmos.bank',
 'pyband.proto.cosmos.bank.module',
 'pyband.proto.cosmos.bank.module.v1',
 'pyband.proto.cosmos.bank.v1beta1',
 'pyband.proto.cosmos.base',
 'pyband.proto.cosmos.base.abci',
 'pyband.proto.cosmos.base.abci.v1beta1',
 'pyband.proto.cosmos.base.node',
 'pyband.proto.cosmos.base.node.v1beta1',
 'pyband.proto.cosmos.base.query',
 'pyband.proto.cosmos.base.query.v1beta1',
 'pyband.proto.cosmos.base.reflection',
 'pyband.proto.cosmos.base.reflection.v1beta1',
 'pyband.proto.cosmos.base.reflection.v2alpha1',
 'pyband.proto.cosmos.base.tendermint',
 'pyband.proto.cosmos.base.tendermint.v1beta1',
 'pyband.proto.cosmos.base.v1beta1',
 'pyband.proto.cosmos.circuit',
 'pyband.proto.cosmos.circuit.module',
 'pyband.proto.cosmos.circuit.module.v1',
 'pyband.proto.cosmos.circuit.v1',
 'pyband.proto.cosmos.consensus',
 'pyband.proto.cosmos.consensus.module',
 'pyband.proto.cosmos.consensus.module.v1',
 'pyband.proto.cosmos.consensus.v1',
 'pyband.proto.cosmos.crisis',
 'pyband.proto.cosmos.crisis.module',
 'pyband.proto.cosmos.crisis.module.v1',
 'pyband.proto.cosmos.crisis.v1beta1',
 'pyband.proto.cosmos.crypto',
 'pyband.proto.cosmos.crypto.ed25519',
 'pyband.proto.cosmos.crypto.hd',
 'pyband.proto.cosmos.crypto.hd.v1',
 'pyband.proto.cosmos.crypto.keyring',
 'pyband.proto.cosmos.crypto.keyring.v1',
 'pyband.proto.cosmos.crypto.multisig',
 'pyband.proto.cosmos.crypto.multisig.v1beta1',
 'pyband.proto.cosmos.crypto.secp256k1',
 'pyband.proto.cosmos.crypto.secp256r1',
 'pyband.proto.cosmos.distribution',
 'pyband.proto.cosmos.distribution.module',
 'pyband.proto.cosmos.distribution.module.v1',
 'pyband.proto.cosmos.distribution.v1beta1',
 'pyband.proto.cosmos.evidence',
 'pyband.proto.cosmos.evidence.module',
 'pyband.proto.cosmos.evidence.module.v1',
 'pyband.proto.cosmos.evidence.v1beta1',
 'pyband.proto.cosmos.feegrant',
 'pyband.proto.cosmos.feegrant.module',
 'pyband.proto.cosmos.feegrant.module.v1',
 'pyband.proto.cosmos.feegrant.v1beta1',
 'pyband.proto.cosmos.genutil',
 'pyband.proto.cosmos.genutil.module',
 'pyband.proto.cosmos.genutil.module.v1',
 'pyband.proto.cosmos.genutil.v1beta1',
 'pyband.proto.cosmos.gov',
 'pyband.proto.cosmos.gov.module',
 'pyband.proto.cosmos.gov.module.v1',
 'pyband.proto.cosmos.gov.v1',
 'pyband.proto.cosmos.gov.v1beta1',
 'pyband.proto.cosmos.group',
 'pyband.proto.cosmos.group.module',
 'pyband.proto.cosmos.group.module.v1',
 'pyband.proto.cosmos.group.v1',
 'pyband.proto.cosmos.mint',
 'pyband.proto.cosmos.mint.module',
 'pyband.proto.cosmos.mint.module.v1',
 'pyband.proto.cosmos.mint.v1beta1',
 'pyband.proto.cosmos.msg',
 'pyband.proto.cosmos.msg.textual',
 'pyband.proto.cosmos.msg.textual.v1',
 'pyband.proto.cosmos.msg.v1',
 'pyband.proto.cosmos.nft',
 'pyband.proto.cosmos.nft.module',
 'pyband.proto.cosmos.nft.module.v1',
 'pyband.proto.cosmos.nft.v1beta1',
 'pyband.proto.cosmos.orm',
 'pyband.proto.cosmos.orm.module',
 'pyband.proto.cosmos.orm.module.v1alpha1',
 'pyband.proto.cosmos.orm.query',
 'pyband.proto.cosmos.orm.query.v1alpha1',
 'pyband.proto.cosmos.orm.v1',
 'pyband.proto.cosmos.orm.v1alpha1',
 'pyband.proto.cosmos.params',
 'pyband.proto.cosmos.params.module',
 'pyband.proto.cosmos.params.module.v1',
 'pyband.proto.cosmos.params.v1beta1',
 'pyband.proto.cosmos.query',
 'pyband.proto.cosmos.query.v1',
 'pyband.proto.cosmos.reflection',
 'pyband.proto.cosmos.reflection.v1',
 'pyband.proto.cosmos.slashing',
 'pyband.proto.cosmos.slashing.module',
 'pyband.proto.cosmos.slashing.module.v1',
 'pyband.proto.cosmos.slashing.v1beta1',
 'pyband.proto.cosmos.staking',
 'pyband.proto.cosmos.staking.module',
 'pyband.proto.cosmos.staking.module.v1',
 'pyband.proto.cosmos.staking.v1beta1',
 'pyband.proto.cosmos.store',
 'pyband.proto.cosmos.store.internal',
 'pyband.proto.cosmos.store.internal.kv',
 'pyband.proto.cosmos.store.internal.kv.v1beta1',
 'pyband.proto.cosmos.store.snapshots',
 'pyband.proto.cosmos.store.snapshots.v1',
 'pyband.proto.cosmos.store.streaming',
 'pyband.proto.cosmos.store.streaming.abci',
 'pyband.proto.cosmos.store.v1beta1',
 'pyband.proto.cosmos.tx',
 'pyband.proto.cosmos.tx.config',
 'pyband.proto.cosmos.tx.config.v1',
 'pyband.proto.cosmos.tx.signing',
 'pyband.proto.cosmos.tx.signing.v1beta1',
 'pyband.proto.cosmos.tx.v1beta1',
 'pyband.proto.cosmos.upgrade',
 'pyband.proto.cosmos.upgrade.module',
 'pyband.proto.cosmos.upgrade.module.v1',
 'pyband.proto.cosmos.upgrade.v1beta1',
 'pyband.proto.cosmos.vesting',
 'pyband.proto.cosmos.vesting.module',
 'pyband.proto.cosmos.vesting.module.v1',
 'pyband.proto.cosmos.vesting.v1beta1',
 'pyband.proto.cosmos_proto',
 'pyband.proto.gogoproto',
 'pyband.proto.google',
 'pyband.proto.google.api',
 'pyband.proto.tendermint',
 'pyband.proto.tendermint.abci',
 'pyband.proto.tendermint.crypto',
 'pyband.proto.tendermint.libs',
 'pyband.proto.tendermint.libs.bits',
 'pyband.proto.tendermint.p2p',
 'pyband.proto.tendermint.types',
 'pyband.proto.tendermint.version',
 'pyband.wallet']

package_data = \
{'': ['*']}

install_requires = \
['bech32==1.2.0',
 'betterproto==2.0.0b7',
 'bip32==0.0.8',
 'ecdsa==0.19.0',
 'grpclib==0.4.3',
 'ledgerblue>=0.1.54,<0.2.0',
 'mnemonic==0.19',
 'python-dateutil==2.8.2']

setup_kwargs = {
    'name': 'pyband',
    'version': '0.4.0rc1',
    'description': 'Python library for BandChain',
    'long_description': '<div align="center">\n    <h2>PyBand</h2>\n    <blockquote>BandChain Python Library</blockquote>\n</div>\n\nPyband is a library that is used to interact with BandChain through the `gRPC` protocol. Querying data and sending\ntransaction can be done here!\n\n## ⭐️ Features\n\nThis helper library allows users to interact with BandChain.\n\nPyBand supports the following features:\n\n- Getting the information of a specific oracle script, data source, and request ID.\n- Getting the account information of specific address.\n- Getting the latest request for a specific oracle script with its matching calldata and validator ask_count and\n  min_count.\n- Querying all the reporters associated with a specific validator.\n- Seeing what client_id you are using and getting BandChain\'s latest block data.\n- Able to send transaction in 3 modes: block mode, async mode, and sync mode.\n\n## 📦 Installation\n\nThis library is available on [PyPI](https://pypi.org/project/pyband/)\n\n```bash\npip install pyband\n```\n\n## 💎 Example Usage\n\nThe example below shows how this library can be used to get the result of the latest request for the price of any\ncryptocurrency. In this example, we will get the latest price of BTC on BandChain\'s testnet.\n\nThe specified parameters are:\n\n- `oracleScriptID`: 111\n- `calldata`: The hex string representing the [OBI](<https://github.com/bandprotocol/bandchain/wiki/Oracle-Binary-Encoding-(OBI)>)-encoded value of `{\'symbols\': [\'BTC\'], \'multiplier\': 100000000}`\n- `minCount`: 10\n- `askCount`: 16\n\n```python\nimport asyncio\n\nfrom pyband import Client, PyObi\n\n\nasync def main():\n    grpc_url = "laozi-testnet6.bandchain.org"\n    c = Client.from_endpoint(grpc_url, 443)\n\n    oid = 111\n    calldata = "00000001000000034254430000000005f5e100"\n    min_count = 10\n    ask_count = 16\n\n    req_info = await c.get_latest_request(oid, calldata, min_count, ask_count)\n    oracle_script = await c.get_oracle_script(oid)\n    obi = PyObi(oracle_script.schema)\n\n    # Converts the calldata into a readable syntax\n    print(obi.decode_input(bytes.fromhex(calldata)))\n\n    # Prints the result\n    print(obi.decode_output(req_info.request.result.result))\n\n\nif __name__ == "__main__":\n    asyncio.run(main())\n```\n\nBelow is the results of the example above.\n\n```\n{\'symbols\': [\'BTC\'], \'multiplier\': 100000000}\n{\'rates\': [1936488410000]}\n```\n\nThis example shows how to send a transaction on BandChain using block mode.\n\n```python\nimport asyncio\nimport os\n\nfrom pyband import Client, Transaction, Wallet\nfrom pyband.messages.cosmos.bank.v1beta1 import MsgSend\nfrom pyband.proto.cosmos.base.v1beta1 import Coin\n\n\nasync def main():\n    # Create a GRPC connection\n    grpc_url = "laozi-testnet6.bandchain.org"\n    c = Client.from_endpoint(grpc_url, 443)\n\n    # Convert a mnemonic to a wallet\n    wallet = Wallet.from_mnemonic(os.getenv("MNEMONIC"))\n    sender = wallet.get_address().to_acc_bech32()\n\n    # Prepare a transaction\'s properties\n    msg_send = MsgSend(\n        from_address=sender,\n        to_address="band19ajhdg6maw0ja0a7qd9sq7nm4ym9f4wjg8r96w",\n        amount=[Coin(amount="1000000", denom="uband")],\n    )\n\n    account = await c.get_account(sender)\n    account_num = account.account_number\n    sequence = account.sequence\n\n    fee = [Coin(amount="50000", denom="uband")]\n    chain_id = await c.get_chain_id()\n\n    # Step 4 Construct a transaction\n    txn = (\n        Transaction()\n        .with_messages(msg_send)\n        .with_sequence(sequence)\n        .with_account_num(account_num)\n        .with_chain_id(chain_id)\n        .with_gas(2000000)\n        .with_fee(fee)\n        .with_memo("")\n    )\n\n    # Sign and broadcast a transaction\n    tx_block = await c.send_tx_sync_mode(wallet.sign_and_build(txn))\n\n    # Converting to JSON for readability\n    print(tx_block.to_json(indent=4))\n\n\nif __name__ == "__main__":\n    asyncio.run(main())\n```\n\n## 🧀 Notes\n\nFor more examples, please go to [`examples`](/examples/request_data_example.py).\n',
    'author': 'Band Protocol',
    'author_email': 'None',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://bandprotocol.com/',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.7,<4.0',
}


setup(**setup_kwargs)
