from dask.dataframe import DataFrame as ddDataFrame, Series as ddSeries
from pandas import Series as pdSeries
from typing import Any

def drop_null(var: ddSeries, is_str: bool = False) -> ddSeries: ...
def get_skewness_level(skewness: int | float) -> tuple: ...
def get_missingness_level(missingness: int | float) -> tuple: ...
def get_cardinality_level(card_level: int | float) -> tuple: ...
def get_duplicate_level(duplicates_ratio: float): ...
def get_email_level(email_ratio: float): ...
def value_counts(ddf: ddDataFrame, memory_ratio: int = 3) -> pdSeries: ...
def dropna(ddf: ddDataFrame, how: str = 'all', memory_ratio: int = 3) -> pdSeries: ...
def is_sequence(value: Any) -> bool: ...
def is_non_negative_number(value: Any) -> bool: ...
