from _typeshed import Incomplete
from pandas import DataFrame as pdDataframe
from ydata.preprocessing.utils import BaseTransformer

class RegexID(BaseTransformer):
    regex: Incomplete
    id_cols: Incomplete
    def __init__(self) -> None: ...
    REGEX_DEFAULT: str
    def fit(self, X: pdDataframe, y: Incomplete | None = None, regex_expression: dict = None, columns: list | str = None): ...
    def transform(self, X: pdDataframe, y: Incomplete | None = None) -> pdDataframe: ...
    def inverse_transform(self, X: pdDataframe) -> pdDataframe: ...
