import pandas as pd
from ydata.report.metrics.top_bottom_metric import TopBottomMetric

class CategoryCoverage(TopBottomMetric):
    def __init__(self, formatter=...) -> None: ...
    @property
    def name(self) -> str: ...

class MissingCategoryCoverage(TopBottomMetric):
    def __init__(self, formatter=...) -> None: ...
    @property
    def name(self) -> str: ...

class RangeCoverage(TopBottomMetric):
    def __init__(self, formatter=...) -> None: ...
    @property
    def name(self) -> str: ...
    def get_minmax(self, dataset: pd.DataFrame): ...
