from _typeshed import Incomplete
from collections.abc import Generator

def get_from_env(keys): ...
def is_protected_type(obj): ...
def get_files_in_current_directory(path) -> Generator[Incomplete]: ...
def append_basename(path, filename): ...
def check_dirname_exists(path, is_dir: bool = False) -> None: ...
def create_tmp(): ...
