# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_tax_code import CustomerTaxCode

class TestCustomerTaxCode(unittest.TestCase):
    """CustomerTaxCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerTaxCode:
        """Test CustomerTaxCode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerTaxCode`
        """
        model = CustomerTaxCode()
        if include_optional:
            return CustomerTaxCode(
                id = '',
                name = ''
            )
        else:
            return CustomerTaxCode(
                id = '',
        )
        """

    def testCustomerTaxCode(self):
        """Test CustomerTaxCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
