# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_adjustment_note_support_document_request import CreateAdjustmentNoteSupportDocumentRequest

class TestCreateAdjustmentNoteSupportDocumentRequest(unittest.TestCase):
    """CreateAdjustmentNoteSupportDocumentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAdjustmentNoteSupportDocumentRequest:
        """Test CreateAdjustmentNoteSupportDocumentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAdjustmentNoteSupportDocumentRequest`
        """
        model = CreateAdjustmentNoteSupportDocumentRequest()
        if include_optional:
            return CreateAdjustmentNoteSupportDocumentRequest(
                document_currency = openapi_client.models.create_support_document_request_document_currency.createSupportDocument_request_documentCurrency(
                    code = '', 
                    rate_value = 1.337, 
                    rate_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                number = 1.337,
                prefix = 'C0',
                note = '01234567891011121314',
                invoice_document_reference = openapi_client.models.create_adjustment_note_support_document_request_invoice_document_reference.createAdjustmentNoteSupportDocument_request_invoiceDocumentReference(
                    id = '0', 
                    full_number = '', 
                    cuds = '', 
                    date = '', ),
                discrepancies = [
                    openapi_client.models.create_adjustment_note_support_document_request_discrepancies_inner.createAdjustmentNoteSupportDocument_request_discrepancies_inner(
                        response_code = 1, 
                        description = '012345678910111213141516171819', )
                    ],
                company = openapi_client.models.create_adjustment_note_support_document_request_company.createAdjustmentNoteSupportDocument_request_company(
                    id = '', 
                    organization_type = 1, 
                    identification_number = '', 
                    dv = '0', 
                    name = '0', 
                    regime_code = 'R-99-PN;O-15;O-47;O-48;R-99-PN;O-15;O-15;R-99-PN;R-99-PN;R-99-PN;R-99-PN;O-47;R-99-PN;O-15;O-23;O-47;O-15;O-15;O-15;O-47;O-47;R-99-PN;O-48;R-99-PN;O-49;R-99-PN;O-49;O-48;O-49', 
                    tax_code = openapi_client.models.create_adjustment_note_support_document_request_company_tax_code.createAdjustmentNoteSupportDocument_request_company_taxCode(
                        id = '01', ), ),
                supplier = openapi_client.models.create_adjustment_note_support_document_request_supplier.createAdjustmentNoteSupportDocument_request_supplier(
                    name = '', 
                    origin = '10', 
                    organization_type = 1, 
                    identification_type = '', 
                    identification_number = '', 
                    dv = '0', 
                    regime_code = 'R-99-PN;O-15;O-47;O-48;R-99-PN;O-15;O-15;R-99-PN;R-99-PN;R-99-PN;R-99-PN;O-47;R-99-PN;O-15;O-23;O-47;O-15;O-15;O-15;O-47;O-47;R-99-PN;O-48;R-99-PN;O-49;R-99-PN;O-49;O-48;O-49', 
                    tax_code = '01', 
                    address = openapi_client.models.create_adjustment_note_support_document_request_supplier_address.createAdjustmentNoteSupportDocument_request_supplier_address(
                        address = '', 
                        city = '', 
                        department = '', 
                        postal_code = '012345', 
                        country = '', ), ),
                items = [
                    openapi_client.models.create_adjustment_note_support_document_request_items_inner.createAdjustmentNoteSupportDocument_request_items_inner(
                        standard_code = openapi_client.models.create_support_document_request_items_inner_standard_code.createSupportDocument_request_items_inner_standardCode(
                            identification_id = '', 
                            id = '001', ), 
                        sellers_item_identification = '0', 
                        description = '0', 
                        pack_size = 0, 
                        brand_name = '0', 
                        model_name = '0', 
                        price = 1.337, 
                        discount = 1.337, 
                        discount_amount = 1.337, 
                        charge = 1.337, 
                        charge_amount = 1.337, 
                        quantity = 1.337, 
                        unit_code = '', 
                        note = '', 
                        subtotal = 1.337, 
                        tax_amount = 1.337, 
                        taxes = [
                            openapi_client.models.create_support_document_request_items_inner_taxes_inner.createSupportDocument_request_items_inner_taxes_inner(
                                tax_code = '01', 
                                tax_amount = 1.337, 
                                tax_percentage = '0', 
                                taxable_amount = 1.337, )
                            ], )
                    ],
                total_amounts = openapi_client.models.create_support_document_request_total_amounts.createSupportDocument_request_totalAmounts(
                    gross_total = 1.337, 
                    taxable_total = 1.337, 
                    tax_total = 1.337, 
                    discount_total = 1.337, 
                    charge_total = 1.337, 
                    payable_total = 1.337, ),
                payments = [
                    openapi_client.models.create_adjustment_note_support_document_request_payments_inner.createAdjustmentNoteSupportDocument_request_payments_inner(
                        payment_form = '1', 
                        payment_method = '', 
                        payment_due_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        payment_id = '0', )
                    ],
                discounts_and_charges = [
                    openapi_client.models.create_adjustment_note_support_document_request_discounts_and_charges_inner.createAdjustmentNoteSupportDocument_request_discountsAndCharges_inner(
                        is_charge = True, 
                        reason = '', 
                        percentage_amount = 0, 
                        amount = 0, 
                        base_amount = 0, )
                    ],
                order_reference = openapi_client.models.create_support_document_request_order_reference.createSupportDocument_request_orderReference(
                    id = '', 
                    issue_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
            )
        else:
            return CreateAdjustmentNoteSupportDocumentRequest(
                number = 1.337,
                invoice_document_reference = openapi_client.models.create_adjustment_note_support_document_request_invoice_document_reference.createAdjustmentNoteSupportDocument_request_invoiceDocumentReference(
                    id = '0', 
                    full_number = '', 
                    cuds = '', 
                    date = '', ),
                discrepancies = [
                    openapi_client.models.create_adjustment_note_support_document_request_discrepancies_inner.createAdjustmentNoteSupportDocument_request_discrepancies_inner(
                        response_code = 1, 
                        description = '012345678910111213141516171819', )
                    ],
                company = openapi_client.models.create_adjustment_note_support_document_request_company.createAdjustmentNoteSupportDocument_request_company(
                    id = '', 
                    organization_type = 1, 
                    identification_number = '', 
                    dv = '0', 
                    name = '0', 
                    regime_code = 'R-99-PN;O-15;O-47;O-48;R-99-PN;O-15;O-15;R-99-PN;R-99-PN;R-99-PN;R-99-PN;O-47;R-99-PN;O-15;O-23;O-47;O-15;O-15;O-15;O-47;O-47;R-99-PN;O-48;R-99-PN;O-49;R-99-PN;O-49;O-48;O-49', 
                    tax_code = openapi_client.models.create_adjustment_note_support_document_request_company_tax_code.createAdjustmentNoteSupportDocument_request_company_taxCode(
                        id = '01', ), ),
                supplier = openapi_client.models.create_adjustment_note_support_document_request_supplier.createAdjustmentNoteSupportDocument_request_supplier(
                    name = '', 
                    origin = '10', 
                    organization_type = 1, 
                    identification_type = '', 
                    identification_number = '', 
                    dv = '0', 
                    regime_code = 'R-99-PN;O-15;O-47;O-48;R-99-PN;O-15;O-15;R-99-PN;R-99-PN;R-99-PN;R-99-PN;O-47;R-99-PN;O-15;O-23;O-47;O-15;O-15;O-15;O-47;O-47;R-99-PN;O-48;R-99-PN;O-49;R-99-PN;O-49;O-48;O-49', 
                    tax_code = '01', 
                    address = openapi_client.models.create_adjustment_note_support_document_request_supplier_address.createAdjustmentNoteSupportDocument_request_supplier_address(
                        address = '', 
                        city = '', 
                        department = '', 
                        postal_code = '012345', 
                        country = '', ), ),
                items = [
                    openapi_client.models.create_adjustment_note_support_document_request_items_inner.createAdjustmentNoteSupportDocument_request_items_inner(
                        standard_code = openapi_client.models.create_support_document_request_items_inner_standard_code.createSupportDocument_request_items_inner_standardCode(
                            identification_id = '', 
                            id = '001', ), 
                        sellers_item_identification = '0', 
                        description = '0', 
                        pack_size = 0, 
                        brand_name = '0', 
                        model_name = '0', 
                        price = 1.337, 
                        discount = 1.337, 
                        discount_amount = 1.337, 
                        charge = 1.337, 
                        charge_amount = 1.337, 
                        quantity = 1.337, 
                        unit_code = '', 
                        note = '', 
                        subtotal = 1.337, 
                        tax_amount = 1.337, 
                        taxes = [
                            openapi_client.models.create_support_document_request_items_inner_taxes_inner.createSupportDocument_request_items_inner_taxes_inner(
                                tax_code = '01', 
                                tax_amount = 1.337, 
                                tax_percentage = '0', 
                                taxable_amount = 1.337, )
                            ], )
                    ],
                total_amounts = openapi_client.models.create_support_document_request_total_amounts.createSupportDocument_request_totalAmounts(
                    gross_total = 1.337, 
                    taxable_total = 1.337, 
                    tax_total = 1.337, 
                    discount_total = 1.337, 
                    charge_total = 1.337, 
                    payable_total = 1.337, ),
                payments = [
                    openapi_client.models.create_adjustment_note_support_document_request_payments_inner.createAdjustmentNoteSupportDocument_request_payments_inner(
                        payment_form = '1', 
                        payment_method = '', 
                        payment_due_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        payment_id = '0', )
                    ],
        )
        """

    def testCreateAdjustmentNoteSupportDocumentRequest(self):
        """Test CreateAdjustmentNoteSupportDocumentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
