# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_companies200_response_companies_inner_webhooks_credit_notes import GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes

class TestGetCompanies200ResponseCompaniesInnerWebhooksCreditNotes(unittest.TestCase):
    """GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes:
        """Test GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes`
        """
        model = GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes()
        if include_optional:
            return GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes(
                emission_finished = openapi_client.models.get_companies_200_response_companies_inner_webhooks_credit_notes_emission_finished.getCompanies_200_response_companies_inner_webhooks_creditNotes_emissionFinished(
                    url = '', 
                    headers = openapi_client.models.headers.headers(), 
                    status = 'active', )
            )
        else:
            return GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes(
                emission_finished = openapi_client.models.get_companies_200_response_companies_inner_webhooks_credit_notes_emission_finished.getCompanies_200_response_companies_inner_webhooks_creditNotes_emissionFinished(
                    url = '', 
                    headers = openapi_client.models.headers.headers(), 
                    status = 'active', ),
        )
        """

    def testGetCompanies200ResponseCompaniesInnerWebhooksCreditNotes(self):
        """Test GetCompanies200ResponseCompaniesInnerWebhooksCreditNotes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
