# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_adjustment_note_support_document_request_items_inner import CreateAdjustmentNoteSupportDocumentRequestItemsInner

class TestCreateAdjustmentNoteSupportDocumentRequestItemsInner(unittest.TestCase):
    """CreateAdjustmentNoteSupportDocumentRequestItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAdjustmentNoteSupportDocumentRequestItemsInner:
        """Test CreateAdjustmentNoteSupportDocumentRequestItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAdjustmentNoteSupportDocumentRequestItemsInner`
        """
        model = CreateAdjustmentNoteSupportDocumentRequestItemsInner()
        if include_optional:
            return CreateAdjustmentNoteSupportDocumentRequestItemsInner(
                standard_code = openapi_client.models.create_support_document_request_items_inner_standard_code.createSupportDocument_request_items_inner_standardCode(
                    identification_id = '', 
                    id = '001', ),
                sellers_item_identification = '0',
                description = '0',
                pack_size = 0,
                brand_name = '0',
                model_name = '0',
                price = 1.337,
                discount = 1.337,
                discount_amount = 1.337,
                charge = 1.337,
                charge_amount = 1.337,
                quantity = 1.337,
                unit_code = '',
                note = '',
                subtotal = 1.337,
                tax_amount = 1.337,
                taxes = [
                    openapi_client.models.create_support_document_request_items_inner_taxes_inner.createSupportDocument_request_items_inner_taxes_inner(
                        tax_code = '01', 
                        tax_amount = 1.337, 
                        tax_percentage = '0', 
                        taxable_amount = 1.337, )
                    ]
            )
        else:
            return CreateAdjustmentNoteSupportDocumentRequestItemsInner(
                standard_code = openapi_client.models.create_support_document_request_items_inner_standard_code.createSupportDocument_request_items_inner_standardCode(
                    identification_id = '', 
                    id = '001', ),
                description = '0',
                price = 1.337,
                quantity = 1.337,
                unit_code = '',
                subtotal = 1.337,
                tax_amount = 1.337,
        )
        """

    def testCreateAdjustmentNoteSupportDocumentRequestItemsInner(self):
        """Test CreateAdjustmentNoteSupportDocumentRequestItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
