# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_support_document_request_items_inner_standard_code import CreateSupportDocumentRequestItemsInnerStandardCode

class TestCreateSupportDocumentRequestItemsInnerStandardCode(unittest.TestCase):
    """CreateSupportDocumentRequestItemsInnerStandardCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSupportDocumentRequestItemsInnerStandardCode:
        """Test CreateSupportDocumentRequestItemsInnerStandardCode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSupportDocumentRequestItemsInnerStandardCode`
        """
        model = CreateSupportDocumentRequestItemsInnerStandardCode()
        if include_optional:
            return CreateSupportDocumentRequestItemsInnerStandardCode(
                identification_id = '',
                id = '001'
            )
        else:
            return CreateSupportDocumentRequestItemsInnerStandardCode(
                identification_id = '',
        )
        """

    def testCreateSupportDocumentRequestItemsInnerStandardCode(self):
        """Test CreateSupportDocumentRequestItemsInnerStandardCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
