# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_event_request_issuer_party import CreateEventRequestIssuerParty

class TestCreateEventRequestIssuerParty(unittest.TestCase):
    """CreateEventRequestIssuerParty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEventRequestIssuerParty:
        """Test CreateEventRequestIssuerParty
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEventRequestIssuerParty`
        """
        model = CreateEventRequestIssuerParty()
        if include_optional:
            return CreateEventRequestIssuerParty(
                identification_type = '11',
                dv = '',
                identification_number = '',
                first_name = '',
                family_name = '',
                job_title = '',
                organization_department = ''
            )
        else:
            return CreateEventRequestIssuerParty(
        )
        """

    def testCreateEventRequestIssuerParty(self):
        """Test CreateEventRequestIssuerParty"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
