# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_support_document_request_items_inner_taxes_inner import CreateSupportDocumentRequestItemsInnerTaxesInner

class TestCreateSupportDocumentRequestItemsInnerTaxesInner(unittest.TestCase):
    """CreateSupportDocumentRequestItemsInnerTaxesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSupportDocumentRequestItemsInnerTaxesInner:
        """Test CreateSupportDocumentRequestItemsInnerTaxesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSupportDocumentRequestItemsInnerTaxesInner`
        """
        model = CreateSupportDocumentRequestItemsInnerTaxesInner()
        if include_optional:
            return CreateSupportDocumentRequestItemsInnerTaxesInner(
                tax_code = '01',
                tax_amount = 1.337,
                tax_percentage = '0',
                taxable_amount = 1.337
            )
        else:
            return CreateSupportDocumentRequestItemsInnerTaxesInner(
                tax_code = '01',
                tax_amount = 1.337,
                tax_percentage = '0',
                taxable_amount = 1.337,
        )
        """

    def testCreateSupportDocumentRequestItemsInnerTaxesInner(self):
        """Test CreateSupportDocumentRequestItemsInnerTaxesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
