import numpy as np

def round_preserving_row_totals(confident_joint: np.ndarray) -> np.ndarray: ...
def calibrate_confident_joint(confident_joint: np.ndarray, labels: list | np.ndarray, label_counts: np.ndarray) -> np.ndarray: ...
def compute_confident_joint(labels, label_counts: np.ndarray, pred_probs: np.ndarray, *, thresholds: np.ndarray | list | None = None, calibrate: bool = True, return_indices_of_off_diagonals: bool = False): ...
