from dataclasses import dataclass

@dataclass
class RBIGConfig:
    uniformizer: str = ...
    bins: int | str = ...
    alpha: float = ...
    bound_ext: float = ...
    eps: float = ...
    rotation: str = ...
    zero_tolerance: int = ...
    max_layers: int = ...
    random_state: int | None = ...
    max_iter: int = ...
    domain_hint: list[float] | None = ...
    def __init__(self, uniformizer=..., bins=..., alpha=..., bound_ext=..., eps=..., rotation=..., zero_tolerance=..., max_layers=..., random_state=..., max_iter=..., domain_hint=...) -> None: ...
