# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.eventos_electrnicos_api import EventosElectrnicosApi


class TestEventosElectrnicosApi(unittest.TestCase):
    """EventosElectrnicosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventosElectrnicosApi()

    def tearDown(self) -> None:
        pass

    def test_create_event(self) -> None:
        """Test case for create_event

        Endpoint para emitir un evento relacionado a una factura electrónica
        """
        pass

    def test_create_event_from_xml(self) -> None:
        """Test case for create_event_from_xml

        Endpoint para emitir un evento relacionado a una factura electrónica a partir de su AttachedDocument
        """
        pass

    def test_get_event(self) -> None:
        """Test case for get_event

        Endpoint para consultar la información de un evento por su id
        """
        pass

    def test_get_event_file(self) -> None:
        """Test case for get_event_file

        Endpoint para obtener un archivo asociado a un evento electrónico
        """
        pass

    def test_get_invoice_events(self) -> None:
        """Test case for get_invoice_events

        Endpoint para consultar los eventos asociados a una factura hasta la fecha
        """
        pass


if __name__ == '__main__':
    unittest.main()
