# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_invoice_events200_response_events_inner_document_reference import GetInvoiceEvents200ResponseEventsInnerDocumentReference

class TestGetInvoiceEvents200ResponseEventsInnerDocumentReference(unittest.TestCase):
    """GetInvoiceEvents200ResponseEventsInnerDocumentReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInvoiceEvents200ResponseEventsInnerDocumentReference:
        """Test GetInvoiceEvents200ResponseEventsInnerDocumentReference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInvoiceEvents200ResponseEventsInnerDocumentReference`
        """
        model = GetInvoiceEvents200ResponseEventsInnerDocumentReference()
        if include_optional:
            return GetInvoiceEvents200ResponseEventsInnerDocumentReference(
                number = '',
                uuid = ''
            )
        else:
            return GetInvoiceEvents200ResponseEventsInnerDocumentReference(
        )
        """

    def testGetInvoiceEvents200ResponseEventsInnerDocumentReference(self):
        """Test GetInvoiceEvents200ResponseEventsInnerDocumentReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
