# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_companies200_response_companies_inner_address import GetCompanies200ResponseCompaniesInnerAddress

class TestGetCompanies200ResponseCompaniesInnerAddress(unittest.TestCase):
    """GetCompanies200ResponseCompaniesInnerAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCompanies200ResponseCompaniesInnerAddress:
        """Test GetCompanies200ResponseCompaniesInnerAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCompanies200ResponseCompaniesInnerAddress`
        """
        model = GetCompanies200ResponseCompaniesInnerAddress()
        if include_optional:
            return GetCompanies200ResponseCompaniesInnerAddress(
                address = '',
                city = '',
                department = '',
                country = ''
            )
        else:
            return GetCompanies200ResponseCompaniesInnerAddress(
        )
        """

    def testGetCompanies200ResponseCompaniesInnerAddress(self):
        """Test GetCompanies200ResponseCompaniesInnerAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
