
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-23T13:20:48+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4dc834e51051244439063a8b1a604207189d345",
 "version": "1.0.8rc28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
