options = {
    "ipv4_only": "-4",
    "ipv6_only": "-6",
    "enable_agent_forwarding": "-A",
    "disable_agent_forwarding": "-a",
    "bind_interface": "-B",
    "bind_address": "-b",
    "compression": "-C",
    "cipher_spec": "-c",
    "dynamic_port_forwarding": "-D",
    "debug_log_file": "-E",
    "escape_char": "-e",
    "config_file": "-F",
    "background": "-f",
    "print_config": "-G",
    "port": "-p",
    "remote_forward_ports": "-g",
    "pkcs11_provider": "-I",
    "identity_file": "-i",
    "jump_host": "-J",
    "enable_gssapi_auth": "-K",
    "disable_gssapi_auth": "-k",
    "login_name": "-l",
    "master_mode": "-M",
    "mac_spec": "-m",
    "no_remote_command": "-N",
    "no_stdin": "-n",
    "control_master": "-O",
    "query_option": "-Q",
    "quiet": "-q",
    "control_socket": "-S",
    "subsystem": "-s",
    "disable_pty": "-T",
    "force_pty": "-t",
    "version": "-V",
    "verbose": "-v",
    "stdio_forwarding": "-W",
    "tunnel_device": "-w",
    "enable_x11_forwarding": "-X",
    "disable_x11_forwarding": "-x",
    "trusted_x11_forwarding": "-Y",
    "syslog": "-y",
}

ssh_options = {
    "AddKeysToAgent",
    "AddressFamily",
    "BatchMode",
    "BindAddress",
    "CanonicalDomains",
    "CanonicalizeFallbackLocal",
    "CanonicalizeHostname",
    "CanonicalizeMaxDots",
    "CanonicalizePermittedCNAMEs",
    "CASignatureAlgorithms",
    "CertificateFile",
    "ChallengeResponseAuthentication",
    "CheckHostIP",
    "Ciphers",
    "ClearAllForwardings",
    "Compression",
    "ConnectionAttempts",
    "ConnectTimeout",
    "ControlMaster",
    "ControlPath",
    "ControlPersist",
    "DynamicForward",
    "EscapeChar",
    "ExitOnForwardFailure",
    "FingerprintHash",
    "ForwardAgent",
    "ForwardX11",
    "ForwardX11Timeout",
    "ForwardX11Trusted",
    "GatewayPorts",
    "GlobalKnownHostsFile",
    "GSSAPIAuthentication",
    "GSSAPIKeyExchange",
    "GSSAPIClientIdentity",
    "GSSAPIDelegateCredentials",
    "GSSAPIKexAlgorithms",
    "GSSAPIRenewalForcesRekey",
    "GSSAPIServerIdentity",
    "GSSAPITrustDns",
    "HashKnownHosts",
    "Host",
    "HostbasedAuthentication",
    "HostbasedKeyTypes",
    "HostKeyAlgorithms",
    "HostKeyAlias",
    "Hostname",
    "IdentitiesOnly",
    "IdentityAgent",
    "IdentityFile",
    "IPQoS",
    "KbdInteractiveAuthentication",
    "KbdInteractiveDevices",
    "KexAlgorithms",
    "LocalCommand",
    "LocalForward",
    "LogLevel",
    "MACs",
    "Match",
    "NoHostAuthenticationForLocalhost",
    "NumberOfPasswordPrompts",
    "PasswordAuthentication",
    "PermitLocalCommand",
    "PKCS11Provider",
    "Port",
    "PreferredAuthentications",
    "ProxyCommand",
    "ProxyJump",
    "ProxyUseFdpass",
    "PubkeyAcceptedKeyTypes",
    "PubkeyAuthentication",
    "RekeyLimit",
    "RemoteCommand",
    "RemoteForward",
    "RequestTTY",
    "SendEnv",
    "ServerAliveInterval",
    "ServerAliveCountMax",
    "SetEnv",
    "StreamLocalBindMask",
    "StreamLocalBindUnlink",
    "StrictHostKeyChecking",
    "TCPKeepAlive",
    "Tunnel",
    "TunnelDevice",
    "UpdateHostKeys",
    "User",
    "UserKnownHostsFile",
    "VerifyHostKeyDNS",
    "VisualHostKey",
    "XAuthLocation",
}
