class MaxIteration(StopIteration): ...
class AnonymizerMaxIteration(Exception): ...
class InvalidAnonymizer(Exception): ...
class InvalidAnonymizerConfig(Exception): ...
class InvalidAnonymizerInputType(Exception): ...
