from pandas import DataFrame as pdDataFrame
from typing import Callable
from ydata.dataset.dataset import Dataset

def check_row_constraint(dataset: Dataset, check: Callable, entity: str | None = None) -> pdDataFrame: ...
def preprocess_series(dataset: Dataset, available_columns: list[str]) -> tuple[Dataset, int]: ...
def check_series_relation(dataset: Dataset, check: Callable, available_columns: list[str]): ...
def require_validate(f: Callable) -> Callable: ...
