from _typeshed import Incomplete
from sklearn.base import BaseEstimator, TransformerMixin

class CyclicalFeatures(BaseEstimator, TransformerMixin):
    maxs: Incomplete
    drop: Incomplete
    cols: Incomplete
    def __init__(self, maxs: list[float] | None = None, drop: bool = True) -> None: ...
    @staticmethod
    def sin(x, max): ...
    @staticmethod
    def cos(x, max): ...
    def fit(self, X, y: Incomplete | None = None): ...
    def transform(self, X, y: Incomplete | None = None): ...
    def inverse_transform(self, X, y: Incomplete | None = None): ...
