# Generated by Django 3.0.5 on 2024-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rds_iam_auth', '0061_auto_20230103_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_lorawan_required',
            field=models.BooleanField(default=False, verbose_name='Lorawan support'),
        ),
    ]
