from _typeshed import Incomplete
from scipy.stats._multivariate import multi_rv_generic as multi_rv_generic

class Bijector:
    def forward(self, X) -> None: ...
    def inverse(self, X) -> None: ...
    def gradient(self, X) -> None: ...

class CompositeBijector(Bijector):
    bijectors: Incomplete
    def __init__(self, bijectors: list[Bijector]) -> None: ...
    def forward(self, X): ...
    def inverse(self, Z): ...
    def gradient(self, X): ...

class FlowModel(CompositeBijector):
    base_dist: Incomplete
    info_loss: Incomplete
    def __init__(self, bijectors: list[Bijector], base_dist) -> None: ...
    def sample(self, n_samples: multi_rv_generic = 10): ...
    def predict_proba(self, X): ...
    def score_samples(self, X): ...
