from ..device import DEV_CPU as DEV_CPU, DEV_GPU_0 as DEV_GPU_0

def set_random_seed(seed) -> None: ...
def get_random_seed(): ...
def dtype_map_torch(vqnet_dtype): ...
def device_map_torch(vqnet_device): ...
def set_grad_enabled(flag) -> None: ...
def get_grad_enabled(): ...
def get_vqnet_device(torch_device): ...
def get_vqnet_dtype(dtype): ...
