# Generated by Django 5.1.2 on 2025-01-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsetting",
            name="bento_config",
            field=models.JSONField(default=dict),
        ),
    ]
