# Generated by Django 5.1.2 on 2025-01-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_chatsetting_bento_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmetric",
            name="embedding_tokens",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="chatmetric",
            name="llm_completion_tokens",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="chatmetric",
            name="llm_prompt_tokens",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="chatmetric",
            name="total_llm_tokens",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
