from _typeshed import Incomplete
from pandas import DataFrame as pdDataFrame
from ydata.quality.outlier.prototype import BaseDetectionOperator

class HBOS(BaseDetectionOperator):
    model: Incomplete
    def __init__(self) -> None: ...
    def fit_predict(self, X: pdDataFrame) -> pdDataFrame: ...
    def fit(self, X: pdDataFrame): ...
    def predict(self, X: pdDataFrame) -> pdDataFrame: ...
