from _typeshed import Incomplete
from pandas import DataFrame as pdDataFrame
from pathlib import Path
from ydata.dataset import Dataset as Dataset
from ydata.metadata import Metadata as Metadata
from ydata.quality.outlier.pipeline import OutlierPipeline
from ydata.quality.outlier.prototype import OutlierCluster

class OutlierEngine:
    pipelines: Incomplete
    clusters: Incomplete
    dataset_len: Incomplete
    def __init__(self, config: str | Path | dict[str, OutlierPipeline] | None = None) -> None: ...
    def fit_predict(self, X: Dataset, metadata: Metadata) -> list[OutlierCluster]: ...
    def get_outlier_clusters(self) -> dict[str, list[OutlierCluster]]: ...
    def represent(self, X: Dataset, pipeline: str | None = None) -> dict[str, pdDataFrame] | pdDataFrame: ...
    def update(self) -> None: ...
    def summary(self, details: bool = False) -> dict: ...
