from dataclasses import dataclass

@dataclass
class Waitable:
    category: str = ...
    start: str = ...
    success: str = ...
    fail: str = ...
    tags: list = ...
    def __init__(self, category=..., start=..., success=..., fail=..., tags=...) -> None: ...
