
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-23T01:48:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "06165f782ca184a1943df9cc10e2368e94c68c70",
 "version": "0.35.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
