from _typeshed import Incomplete
from sklearn.base import BaseEstimator, TransformerMixin

class NumericalFactors(BaseEstimator, TransformerMixin):
    groupby: Incomplete
    default: Incomplete
    def __init__(self, groupby: str, factors: dict | None = None, default: bool = True) -> None: ...
    def fit(self, X, y: Incomplete | None = None): ...
    def transform(self, X, y: Incomplete | None = None): ...
    def inverse_transform(self, X, y: Incomplete | None = None): ...
    def save(self, file_path: str): ...
    @staticmethod
    def load(file_path: str): ...
