from xuiniaDB.main import ETADATABASEEBUCHAYAHUINIABLIATSUKANIKOGDANEUSAIETUHUINIIULOLPORNOKSTAKAKOESMOTRISH
import HuiPornoAscii 

db = ETADATABASEEBUCHAYAHUINIABLIATSUKANIKOGDANEUSAIETUHUINIIULOLPORNOKSTAKAKOESMOTRISH()

db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('p')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('o')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('n')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('.')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('d')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('b')

db.RODI_DATABASU_OT_NEGRA()

db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('p')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('o')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('n')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('.')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('d')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('b')

db.PRIHUIARIT_K_TEXTU_SYMBOL_NAX("x")

db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('p')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('o')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('n')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('.')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('d')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('b')

db.PRIHUIARIT_K_TEXTU_SYMBOL_NAX('m')

db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('p')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('o')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('n')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('.')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('d')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('b')


db.OBKONCHIAT_DATABASU_TEXTOM_NAHUI_NAX(1)

#############################################################################################

db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('p')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('o')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('n')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('.')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('d')
db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('b')


text = db.POLIZAT_KLITOR_DATABASE_NAX(1)

for i in str(text[0]):
    db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('p')
    db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('o')
    db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('n')
    db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('.')
    db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('d')
    db.PRIHUIARIT_K_NAZVANIU_DATABASI_SYMBOL_NAX('b')
    db.PRIHUIARIT_K_TEXTU_SYMBOL_NAX(i)
    # print(i)
text = db.YA_NE_PONIMAYU_ETU_XUINIU_NAHUI_NAX()

print(text)

# db.amogus()
# db.sex_pls()
# HuiPornoAscii.Pornushka('r')


# import coder_decoder 
# a = coder_decoder.code('lox')
# print(a)
# b = coder_decoder.decode(a)
# print(b)