class SegmentSizeWarning(Warning): ...
class PreprocessorException(Exception): ...
class SynthesizerException(Exception): ...
class MissingDeviceException(Exception): ...
class NotFittedException(SynthesizerException, ValueError, AttributeError): ...
class SegmentationStrategyException(Exception): ...
class SampleSizeException(SynthesizerException): ...
class TemporaryPathException(SynthesizerException): ...
class NoInputDataTypesWarning(Warning): ...
