# Generated by Django 5.0.9 on 2025-01-16 13:20

import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_app_systems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsystemassignment',
            old_name='content_type',
            new_name='object_type',
        ),
        migrations.AlterField(
            model_name='appsystem',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterUniqueTogether(
            name='appsystemassignment',
            unique_together={('object_type', 'object_id', 'app_system')},
        ),
    ]
