from ydata.report.metrics.base_metric import BaseMetric

class DistanceCorrelation(BaseMetric):
    def __init__(self, formatter=...) -> None: ...
    def distance_correlation(self, source, synthetic, metadata): ...
    @property
    def name(self) -> str: ...

def distance_distribution(df_real, df_synth, data_types: dict): ...

class DistanceDistribution(BaseMetric):
    def __init__(self, formatter=...) -> None: ...
    @property
    def name(self) -> str: ...

class MutualInfo(BaseMetric):
    def __init__(self, formatter=...) -> None: ...
    @property
    def name(self) -> str: ...

class Autocorrelation(BaseMetric):
    def __init__(self, formatter=..., exclude_entity_col: bool = True) -> None: ...
    @property
    def name(self) -> str: ...
