# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest



class TestS3Instance(unittest.TestCase):
    """S3Instance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3Instance(self):
        """Test S3Instance"""
        # inst = S3Instance()


if __name__ == "__main__":
    unittest.main()
