# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.api.external_api import ExternalApi


class TestExternalApi(unittest.TestCase):
    """ExternalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExternalApi()

    def tearDown(self) -> None:
        pass

    def test_download_data_neurodata_io_download_url_get(self) -> None:
        """Test case for download_data_neurodata_io_download_url_get

        Download Data
        """
        pass

    def test_upload_dataset_mesh_neurodata_io_dataset_id_upload_url_mesh_get(self) -> None:
        """Test case for upload_dataset_mesh_neurodata_io_dataset_id_upload_url_mesh_get

        Upload Dataset Mesh
        """
        pass

    def test_upload_dataset_swb_neurodata_io_dataset_id_upload_url_swb_get(self) -> None:
        """Test case for upload_dataset_swb_neurodata_io_dataset_id_upload_url_swb_get

        Upload Dataset Swb
        """
        pass


if __name__ == "__main__":
    unittest.main()
