# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_db_native_login_user_auth_native_login_post(self) -> None:
        """Test case for auth_db_native_login_user_auth_native_login_post

        Auth:Db-Native.Login
        """
        pass

    def test_auth_db_native_logout_user_auth_native_logout_post(self) -> None:
        """Test case for auth_db_native_logout_user_auth_native_logout_post

        Auth:Db-Native.Logout
        """
        pass


if __name__ == "__main__":
    unittest.main()
