# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.models.pre_signed_s3_upload_url_schema import PreSignedS3UploadUrlSchema


class TestPreSignedS3UploadUrlSchema(unittest.TestCase):
    """PreSignedS3UploadUrlSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreSignedS3UploadUrlSchema:
        """Test PreSignedS3UploadUrlSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PreSignedS3UploadUrlSchema`
        """
        model = PreSignedS3UploadUrlSchema()
        if include_optional:
            return PreSignedS3UploadUrlSchema(
                upload_url = '',
                fields = syndb_api_client.models.fields.Fields()
            )
        else:
            return PreSignedS3UploadUrlSchema(
                upload_url = '',
                fields = syndb_api_client.models.fields.Fields(),
        )
        """

    def testPreSignedS3UploadUrlSchema(self):
        """Test PreSignedS3UploadUrlSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
