# coding: utf-8

"""
    Synapse DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from syndb_api_client.models.user_profile import UserProfile


class TestUserProfile(unittest.TestCase):
    """UserProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserProfile:
        """Test UserProfile
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserProfile`
        """
        model = UserProfile()
        if include_optional:
            return UserProfile(
                id = '',
                email = '',
                is_active = True,
                is_superuser = True,
                is_verified = True,
                scientist_tag = '',
                has_profile_picture = True
            )
        else:
            return UserProfile(
                id = '',
                email = '',
                scientist_tag = '',
                has_profile_picture = True,
        )
        """

    def testUserProfile(self):
        """Test UserProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
