from _typeshed import Incomplete
from ydata.dataset import DatasetType, MultiDataset
from ydata.dataset.schemas.datasets_schema import MultiTableSchema
from ydata.metadata import Metadata

logger: Incomplete

class MultiMetadata:
    dataset_type: Incomplete
    schema: Incomplete
    def __init__(self, multiset: MultiDataset, tables_metadata: dict[str, Metadata] | None = None, dataset_attrs: dict[str, dict] | None = None, dataset_type: dict[str, DatasetType | str] | None = None, schema: MultiTableSchema | None = None) -> None: ...
    @property
    def warnings(self) -> dict: ...
    def compute(self): ...
    def __getitem__(self, key: str) -> Metadata: ...
    def items(self): ...
    def keys(self): ...
    def values(self): ...
    def __iter__(self): ...
    def __delitem__(self, table: str): ...
    def save(self, path: str): ...
    @staticmethod
    def load(path: str) -> Metadata: ...
    def validate_schema(self, other_metadata: MultiMetadata, check_referential_integrity: bool, multiset: MultiDataset | None = None, other_multiset: MultiDataset | None = None) -> dict: ...
    def is_same_schema(self, other_metadata: MultiMetadata, multiset: MultiDataset, other_multiset: MultiDataset) -> bool: ...
    def get_schema_validation_summary(self, other_metadata: MultiMetadata, multiset: MultiDataset, other_multiset: MultiDataset) -> str: ...
    def set_table_dataset_type(self, table_name: str, dataset_type: str | DatasetType, dataset_attrs: dict | None = None): ...
    def set_table_dataset_attrs(self, table_name: str, sortby: str | list, entities: str | list | None = None): ...
