def compute_pairwise_distances(x, y): ...
def gaussian_kernel_matrix(x, y, sigmas): ...
def maximum_mean_discrepancy(x, y, kernel): ...
def mmd_loss(source_samples, target_samples, weight: float = 1.0): ...
