from ydata.report.metrics.top_bottom_metric import TopBottomMetric

class KSTest(TopBottomMetric):
    def __init__(self, formatter=...) -> None: ...
    @property
    def name(self) -> str: ...

class TotalVariationDistance(TopBottomMetric):
    def __init__(self, formatter=...) -> None: ...
    @property
    def name(self) -> str: ...
