from pandas.io.parsers import TextFileReader as TextFileReader
from ydata.connectors.filetype import FileType

def calculate_schema(chunks: TextFileReader) -> dict: ...
def get_schema(file_path: list | str, file_type: FileType, sep: str = ';', storage_options: dict | None = None) -> dict: ...
