# Generated by Django 3.2.25 on 2024-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausleihe', '0011_alter_skillset_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('lsf_id', models.IntegerField(unique=True)),
                ('anzahl_plaetze', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='raeume',
            field=models.ManyToManyField(help_text='In welchen Räumen kann dieser Skill durchgeführt werden?', related_name='skills', to='ausleihe.Raum', verbose_name='verfügbar in'),
        ),
    ]
