# Generated by Django 3.2.25 on 2024-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausleihe', '0013_auto_20241021_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='raeume',
            field=models.ManyToManyField(blank=True, help_text='In welchen Räumen kann dieser Skill durchgeführt werden?', related_name='skills', to='ausleihe.Raum', verbose_name='Räume'),
        ),
    ]
