
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-23T12:23:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbde5e79cf879796aa7e03bf629ea5caee17116c",
 "version": "1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
