
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-23T11:05:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a19b808253d96b2068ec50a11faffa943a554ecb",
 "version": "5.4.90"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
