from _typeshed import Incomplete
from pandas import DataFrame as pdDataFrame
from ydata.dataset.multidataset import MultiDataset as MultiDataset
from ydata.metadata import Metadata as Metadata
from ydata.synthesizers.calculated_features import CalculatedFeature

logger: Incomplete

def init_calculated_features(calculated_features: dict | None): ...
def validate_calculated_features(data: MultiDataset, calculated_features: list[CalculatedFeature]) -> None: ...
def drop_calculated_features_columns(calculated_features: list[CalculatedFeature], tables_df: dict[str, pdDataFrame]): ...
def drop_table_calculated_features_columns(table: str, table_data: pdDataFrame, table_metadata: Metadata, calculated_features: list[CalculatedFeature]): ...
def get_tables_from_columns(columns: list[str]) -> set[str]: ...
def is_intra_table_calculated_feature(calculated_feature: CalculatedFeature) -> bool: ...
def apply_table_calculated_features(calculated_features: list[CalculatedFeature], table: str, table_data: pdDataFrame, sample_tables: dict[str, pdDataFrame]) -> pdDataFrame: ...
