from .NDJSONReader import NDJSONReaderConfiguration
from .Reader import ReaderConfiguration
from .tegracli_reader import TegracliReaderConfiguration
from .TwacapicReader import TwacapicReaderConfiguration
