import numpy as np

def entropy_univariate(X: np.ndarray, bins: int | str = 'auto', correction: bool = True) -> np.ndarray: ...
def entropy_marginal(X: np.ndarray, bins: int | str = 'auto', correction: bool = True) -> np.ndarray: ...
def entropy_rbig(X: np.ndarray, bins: int | str = 'auto', alpha: float = 1e-10, bound_ext: float = 0.3, eps: float = 1e-10, rotation: str = 'PCA', zero_tolerance: int = 60, max_layers: int = 1000, progress_bar: bool = False): ...
