import numpy as np
from _typeshed import Incomplete

def information_reduction(X, Y, bins: str = 'auto', tol_dimensions: Incomplete | None = None, correction: bool = True): ...
def rbig_total_corr(X: np.ndarray, bins: str = 'auto', alpha: float = 1e-10, bound_ext: float = 0.3, eps: float = 1e-10, rotation: str = 'PCA', zero_tolerance: int = 60, max_layers: int = 1000, progress_bar: bool = False) -> float: ...
