from _typeshed import Incomplete

SAMPLE_SIZES: Incomplete

def calculate_wilson_sample_size(n: int, p: float, z: float, e: float) -> int: ...
def calculate_wilson_cc(z: float, n: int, p: float) -> tuple[float, float, float, float]: ...
def determine_z_value(confidence_level: float) -> float: ...
def is_normal(n: int, p: float) -> bool: ...
def calculate_normal_sample_size(confidence_level: float = 0.99, margin_error: float = 0.05) -> int: ...
def calculate_normal_margin_of_error(z_value: float, p: float, sample_size: int): ...
