from pandas import DataFrame

def random_walk_upsample(data: DataFrame, n_upsample: int = 5) -> DataFrame: ...
def linear_interpolation_upsample(data: DataFrame, time_to_resample: str = '10T', add_noise: bool = False, noise_reduction: float = 0.25): ...
def distorted_mean_upsample(data: DataFrame, time_to_resample: str = '10T', linear_interpolated: bool = False): ...
