
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-22T16:38:03-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "85234d1607bccb7d069926777c2c4a53f51e6e27",
 "version": "0.35.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
