from _typeshed import Incomplete
from ydata.connectors.base_connector import BaseConnector
from ydata.connectors.filetype import FileType
from ydata.dataset import Dataset

class LocalConnector(BaseConnector):
    STORAGE_TYPE: Incomplete
    storage_options: Incomplete
    def __init__(self) -> None: ...
    def ls(self, path: str) -> dict[str, list[str]]: ...
    def list(self, path: str, abs_path: bool = False) -> dict[str, list[str]]: ...
    def get_file_paths(self, path: str, file_type: FileType, extension: str) -> list[str]: ...
    def read_sample(self, path: str, file_type: FileType = ..., sample_size: int = ..., sep: str = ',', *args, **kwargs) -> Dataset: ...
    def read_file(self, path: str, file_type: FileType = ..., sample_size: int | None = None, sep: str = ',', has_header: bool = True, columns: list[str] | None = None, schema: dict | None = None, *args, **kwargs) -> Dataset: ...
    def write_file(self, data, path: str, file_type: FileType | None = None, *args, **kwargs): ...
    def test(self) -> None: ...
