from _typeshed import Incomplete

FLOAT_STR_TO_DTYPE: Incomplete
INT_STR_TO_DTYPE: Incomplete

class TypeInference:
    converters: Incomplete
    def __init__(self, converters=()) -> None: ...
    @property
    def inferable_types(self): ...
    def register_converter(self, name, func) -> None: ...
    def get_converter(self, name): ...
    def convert(self, s, include_type: bool = False): ...
    def infer(self, s): ...

DATE_FORMATS: Incomplete
TIME_FORMATS: Incomplete
DATE_TIME_SEPS: Incomplete
true_re: Incomplete
false_re: Incomplete

def convert_bool_int(s): ...
def convert_int(s): ...
def convert_float(s): ...
def convert_bool(s): ...
def convert_string(s): ...
def convert_datetime(s, date_formats=..., time_formats=...): ...
def convert_date(s, date_formats=...): ...
def convert_time(s, time_formats=...): ...

default_inference: Incomplete
DEFAULT_TYPES: Incomplete

class TypeConverter:
    @staticmethod
    def to_low(dtype: str): ...
    @staticmethod
    def from_low(dtype): ...

def infer_MV_code(df, col): ...
