# Generated by Django 3.2.25 on 2024-11-28 15:50

from ausleihe.models.Nutzungsordnung import datierte_nutzungsordnung
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ausleihe', '0023_reservierung_leihe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutzungsordnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erzeugt', models.DateTimeField(auto_now=True)),
                ('datei', models.FileField(upload_to=datierte_nutzungsordnung)),
                ('akzeptiert_von', models.ManyToManyField(blank=True, related_name='akzeptierte_nutzungsordnungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzungsordnung',
                'verbose_name_plural': 'Nutzungsordnungen',
                'ordering': ('-erzeugt',),
            },
        ),
    ]
