from typing import Any

MB_URL: str
MB_VERSION_ID: str
admin_id_: int
token_: str
timeout_: int

def set_admin_id(admin_id: int) -> None: ...
def set_token(token: str) -> None: ...
def set_timeout(timeout: int) -> None: ...
def post_request(path: str, data: dict[str, Any] | None = None, method: str = 'post') -> dict[str, Any]: ...
