from ydata.profiling.profile_report import ProfileReport
from ydata_profiling.config import Settings as Settings

def validate_reports(reports: list[ProfileReport], configs: list[Settings]) -> None: ...
def compare(reports: list[ProfileReport], config: Settings | None = None, compute: bool = False) -> ProfileReport: ...
