"""
    EMIL AccountingService

    The EMIL AccountingService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.accounting
from eis.accounting.model.booking_process_class import BookingProcessClass
globals()['BookingProcessClass'] = BookingProcessClass
from eis.accounting.model.create_booking_process_response_class import CreateBookingProcessResponseClass


class TestCreateBookingProcessResponseClass(unittest.TestCase):
    """CreateBookingProcessResponseClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateBookingProcessResponseClass(self):
        """Test CreateBookingProcessResponseClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateBookingProcessResponseClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
