# Generated by Django 3.2.25 on 2024-10-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausleihe', '0014_alter_skill_raeume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gebaeude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('lsf_id', models.IntegerField(unique=True, verbose_name='LSF ID')),
            ],
            options={
                'verbose_name': 'Gebäude',
                'verbose_name_plural': 'Gebäude',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='raum',
            name='gebaeude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ausleihe.gebaeude', verbose_name='Gebäude'),
        ),
    ]
