# Generated by Django 3.2.25 on 2024-10-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsmedhro_core', '0004_auto_20240304_0915'),
        ('ausleihe', '0019_various_delete_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservierung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(help_text='Für wann gilt die Reservierung?', verbose_name='Datum und Uhrzeit')),
                ('ende', models.DateTimeField(editable=False)),
                ('erzeugt', models.DateTimeField(auto_now=True)),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservierungen', to='ausleihe.medium')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservierungen', to='fsmedhro_core.fachschaftuser')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservierungen', to='ausleihe.raum')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservierungen', to='ausleihe.skill')),
            ],
            options={
                'verbose_name': 'Reservierung',
                'verbose_name_plural': 'Reservierungen',
                'ordering': ('-zeit', 'nutzer', 'skill', 'medium', 'raum'),
            },
        ),
    ]
