import numpy as np

def round_preserving_sum(iterable) -> np.ndarray: ...
def round_preserving_row_totals(confident_joint) -> np.ndarray: ...
def get_confident_thresholds(labels: list | np.ndarray, pred_probs: np.ndarray) -> np.ndarray: ...
def get_normalized_entropy(pred_probs: np.ndarray) -> np.ndarray: ...
