from ydata.__models._synthpop.maps import Smoothing

def visitor_seq_to_predictor_mat(visit_sequence: list[str]): ...
def intialize_smoothing_strategy(smoothing_method: Smoothing, columns: list[str]): ...
def validate_datatypes(enabled_types, columns): ...
