import datetime
from pathkit.base import BasePath as BasePath
from typing import Any, Generator

class LocalPath(BasePath):
    _section = ()
    _creator = None
    @property
    def exists(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def read(self) -> bytes: ...
    def write(self, data: bytes) -> None: ...
    def upload(self, local_path: str) -> None: ...
    def delete(self) -> None: ...
    def mkdir(self) -> None: ...
    def glob(self, pattern: str = '*') -> Generator['LocalPath', Any, Any]: ...
    @property
    def mtime(self) -> datetime.datetime: ...
