# coding: utf-8

# flake8: noqa

"""
    Giphy API

    Giphy API

    The version of the OpenAPI document: 1.0
    Contact: support@giphy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from test_hive_20_ti_client.api.gifs_api import GifsApi
from test_hive_20_ti_client.api.stickers_api import StickersApi

# import ApiClient
from test_hive_20_ti_client.api_response import ApiResponse
from test_hive_20_ti_client.api_client import ApiClient
from test_hive_20_ti_client.configuration import Configuration
from test_hive_20_ti_client.exceptions import OpenApiException
from test_hive_20_ti_client.exceptions import ApiTypeError
from test_hive_20_ti_client.exceptions import ApiValueError
from test_hive_20_ti_client.exceptions import ApiKeyError
from test_hive_20_ti_client.exceptions import ApiAttributeError
from test_hive_20_ti_client.exceptions import ApiException

# import models into sdk package
from test_hive_20_ti_client.models.get_gifs_by_id200_response import GetGifsById200Response
from test_hive_20_ti_client.models.gif import Gif
from test_hive_20_ti_client.models.gif_images import GifImages
from test_hive_20_ti_client.models.gif_images_downsized import GifImagesDownsized
from test_hive_20_ti_client.models.gif_images_downsized_large import GifImagesDownsizedLarge
from test_hive_20_ti_client.models.gif_images_downsized_medium import GifImagesDownsizedMedium
from test_hive_20_ti_client.models.gif_images_downsized_small import GifImagesDownsizedSmall
from test_hive_20_ti_client.models.gif_images_downsized_still import GifImagesDownsizedStill
from test_hive_20_ti_client.models.gif_images_fixed_height import GifImagesFixedHeight
from test_hive_20_ti_client.models.gif_images_fixed_height_downsampled import GifImagesFixedHeightDownsampled
from test_hive_20_ti_client.models.gif_images_fixed_height_small import GifImagesFixedHeightSmall
from test_hive_20_ti_client.models.gif_images_fixed_height_small_still import GifImagesFixedHeightSmallStill
from test_hive_20_ti_client.models.gif_images_fixed_height_still import GifImagesFixedHeightStill
from test_hive_20_ti_client.models.gif_images_fixed_width import GifImagesFixedWidth
from test_hive_20_ti_client.models.gif_images_fixed_width_downsampled import GifImagesFixedWidthDownsampled
from test_hive_20_ti_client.models.gif_images_fixed_width_small import GifImagesFixedWidthSmall
from test_hive_20_ti_client.models.gif_images_fixed_width_small_still import GifImagesFixedWidthSmallStill
from test_hive_20_ti_client.models.gif_images_fixed_width_still import GifImagesFixedWidthStill
from test_hive_20_ti_client.models.gif_images_looping import GifImagesLooping
from test_hive_20_ti_client.models.gif_images_original import GifImagesOriginal
from test_hive_20_ti_client.models.gif_images_original_still import GifImagesOriginalStill
from test_hive_20_ti_client.models.gif_images_preview import GifImagesPreview
from test_hive_20_ti_client.models.gif_images_preview_gif import GifImagesPreviewGif
from test_hive_20_ti_client.models.image import Image
from test_hive_20_ti_client.models.meta import Meta
from test_hive_20_ti_client.models.pagination import Pagination
from test_hive_20_ti_client.models.random_gif200_response import RandomGif200Response
from test_hive_20_ti_client.models.user import User
